server:
  port: 2003

spring:
  application:
    name: seata-account-service
  cloud:
    alibaba:
      seata:
        tx-service-group: SEATA_GROUP #自定义事务组名称需要与seata-server中的对应
    nacos:
      discovery:
        server-addr: 192.168.150.111:1111
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://yzzy.top:3306/seata_account
    username: user
    password: FE2FF25F6A08F101628C33226E21C64A

feign:
  hystrix:
    enabled: false

logging:
  level:
    io:
      seata: info

mybatis:
  mapperLocations: classpath:mapper/*.xml


