server:
  port: 80
spring:
  cloud:
    config:
      enabled: false
# feign配置
feign:
  hystrix:
    # 在feign中开启hystrix功能，默认情况下feign不开启hystrix功能
    enabled: true
  circuitbreaker:
    enabled: true
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
    register-with-eureka: false	 #作为消费者不提供服务，不应该注册自己
hystrix:
  metrics:
    enabled: true
