server:
  port: 3344

spring:
  application:
    name: cloud-config-center #注册进Eureka服务器的微服务名
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/heizhongweihei/netty_rpc.git #GitHub上面的git仓库名字
          username: 15660661509
          password: wangwenlong521
          default-label: master
#          search-paths: #搜索目录
#            - springcloud-config
#      label: master #读取分支
      #启动成功后访问的路径 http://ip:3344/{label}/{application}-{profile}.yml 能访问的配置文件 就表示成功了
      #rabbitmq相关配置
  rabbitmq:
    host: yzzy.top
    port: 5672  #服务端口号，不是web页面端口号
    username: admin
    password: admin
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka,http://localhost:7002/eureka


##rabbitmq相关配置,暴露bus刷新配置的端点 SpringCloud Bus动态刷新全局广播
management:
  endpoints: #暴露bus刷新配置的端点
    web:
      exposure:
        include: 'bus-refresh'





