server:
  port: 2001


spring:
  application:
    name: seata-order-service
  cloud:
#    在这里配置seata的Group已过时，但仍可以生效 ，推荐单独配置
#    alibaba:
#      seata:
#        tx-service-group:  #自定义事务组名称需要与seata-server中的对应
    nacos:
      discovery:
        server-addr: 192.168.150.111:1111

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://yzzy.top:3306/seata_order?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: user
    password: FE2FF25F6A08F101628C33226E21C64A

feign:
  hystrix:
    enabled: false

logging:
  level:
    io:
      seata: info

mybatis:
  mapperLocations: classpath:mapper/*.xml
seata:
  tx-service-group: SEATA_GROUP
