server:
  port: 9001

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
#        server-addr: 192.168.150.111:1111 #配置Nacos集群地址
        server-addr: yzzy.top:8848 #配置Nacos集群地址

#端口暴漏
management:
  endpoints:
    web:
      exposure:
        include: '*'
