server:
  port: 8803

spring:
  application:
    name: cloud-stream-consumer
  cloud:
    stream:
      binders:
        mykafka:
          type: kafka
          environment:
            spring:
              cloud:
                stream:
                  kafka:
                    binder:
                      brokers: http://yzzy.top:9092 #kafka地址，多个可用,隔开
                      auto-add-partitions: true
                      auto-create-topics: true
                      min-partition-count: 1
      bindings: # 服务的整合处理
        input: # 这个名字是一个通道的名称
          destination: kafkaTopic # 表示要使用的Exchange名称定义
          content-type: application/json # 设置消息类型，本次为对象json，如果是文本则设置“text/plain”
          binder: mykafka # 设置要绑定的消息服务的具体设置
#          group: atguiguA  #当加入同一消费者组织后通一次数据只会消费一次

eureka:
  client: # 客户端进行Eureka注册的配置
    service-url:
      defaultZone: http://localhost:7001/eureka,http://localhost:7002/eureka
#  instance:
#    lease-renewal-interval-in-seconds: 2 # 设置心跳的时间间隔（默认是30秒）
#    lease-expiration-duration-in-seconds: 5 # 如果现在超过了5秒的间隔（默认是90秒）
#    instance-id: receive-8803.com  # 在信息列表时显示主机名称
#    prefer-ip-address: true     # 访问的路径变为IP地址
